name: Prose Linting
on: [push, pull_request]

jobs:
  prose:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

        with:
          # Optional
          version: 2.17.0
          
          # Optional
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip

          # Optional
          # config: https://raw.githubusercontent.com/errata-ai/vale/master/.vale.ini

          # Optional
          files: README.md
  